Rate provider pallet
valibre-org/vln-node pull request #89
Opened 2021-04-23 07:25 UTC by stanly-johnson

This pallet allows Liquidity providers to publish rates on chain for off-chain/on-chain transactions.

related #87

2021-04-24 08:32 UTC, olanod requested changes

2021-04-24 08:32 UTC, olanod commented on pallets/rate_provider/src/lib.rs
> +    pub(super) type RateStore<T: Config> = StorageDoubleMap<
To elaborate more on the types of the example, is often more common to use this base/quote naming than form/to and more confusing to mix(form->base?) so we could have a
```rust
struct AssetPair<B, Q> {
    pub base: B,
    pub quote: Q,
}
```
And as convention we would use for example the crypto always as base in our runtime configuration and everywhere so is easier to remember what is what.

For the map I also think we can put our percentage inside a `RateInfo`/`RateDetail`(or just "`Rate`") struct, so later we can add more features like allowing providers to specify a min/max amount they can transact with, fixed costs, maybe the future option of also setting rate by exact price and even encode a "price function" that gives us a rate as function of an amount. Also perhaps a good place to add your combine rates functionality by implementing the `core::ops::Add` trait? Rate might even be an enum so you could do `Rate::Fixed(123) + Rate::Premium(1)` 🤔 wdyt?

2021-04-24 08:32 UTC, olanod commented on pallets/rate_provider/src/lib.rs
> +        type BaseCurrencyId: Parameter + Member + Copy + MaybeSerializeDeserialize + Ord;
`Asset` and `BaseAsset`? 🙂

2021-04-24 08:32 UTC, olanod commented on pallets/rate_provider/src/lib.rs
> +    // Rates provided by an LP, the actual rate is not stored here
In the context of this pallet let's just call them "providers" as the liquidity part is more of a Valiu concept that might not apply for other projects

2021-04-24 09:56 UTC, stanly-johnson commented on pallets/rate_provider/src/lib.rs
> +        type OracleProvider: DataProvider<Self::CurrencyId, Self::OracleValue>;
Are you talking about renaming `OracleProvider` -> `PriceFeed` or replacing `DataProvider` with [DataFeeder](https://github.com/open-web3-stack/open-runtime-module-library/blob/b63b6667a0809165bda20ba57cbe85e1c0687b8c/oracle/src/lib.rs#L323) 🤔

2021-04-24 15:52 UTC, olanod commented on pallets/rate_provider/src/lib.rs
> +        type OracleProvider: DataProvider<Self::CurrencyId, Self::OracleValue>;
Renaming the OracleProvider, the DataProvider bound is the way to go :)

2021-04-24 18:09 UTC, stanly-johnson commented on pallets/rate_provider/src/lib.rs
> +    pub(super) type RateStore<T: Config> = StorageDoubleMap<
> querying for example the list of mediums for a given pair or the list of providers and their rates for a pair+medium which is what I suspect we will be doing more often

I've updated the storage to BTreeMap and added `get_pair_rates` to `RateProvider` to  fetch the list of providers/rates.

2021-04-24 18:14 UTC, stanly-johnson commented on pallets/rate_provider/src/lib.rs
> +    pub(super) type RateStore<T: Config> = StorageDoubleMap<
> For the map I also think we can put our percentage inside a RateInfo/RateDetail(or just "Rate") struct, so later we can add more features like allowing providers to specify a min/max amount they can transact with, fixed costs, maybe the future option of also setting rate by exact price and even encode a "price function" that gives us a rate as function of an amount. Also perhaps a good place to add your combine rates functionality by implementing the core::ops::Add trait

I've converted it to a struct `RateDetail`, and added `RateCombinator` type in the pallet to get access to combine_rate function. I kinda feel this is much more easier for someone who is implementing this pallet for their runtime, also this is similar to the implementation of `orml_oracle`

2021-04-25 15:29 UTC, olanod requested changes
Looking good ;) just a few remarks

2021-04-25 17:24 UTC, stanly-johnson commented on primitives/src/rates.rs
> +pub trait RateProvider<X, M, Z, R, T> {
> This trait might be tooo generic

😆 Fixed

2021-04-26 06:32 UTC, olanod commented on pallets/rate_provider/src/lib.rs
> +        type OracleValue: Parameter + Member + Ord + FixedPointNumber;
```suggestion
        type OracleValue: Parameter + Member + FixedPointNumber;
```

2021-04-26 06:34 UTC, olanod approved these changes

2021-04-26 07:02 UTC, merged